services:
  - type: web
    name: video-stream-backend
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: 46f6663712dba261f75c41f9b4debcbc51c92d8f4fa247340ef987b2ae840990
      - key: DATABASE_URL
        value: sqlite:///./video_stream.db
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: https://video-stream-frontend-lexb.onrender.com
      - key: ENVIRONMENT
        value: production

  - type: web
    name: video-stream-frontend
    env: static
    rootDir: frontend
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    envVars:
      - key: VITE_WS_URL
        value: wss://video-stream-backend-jr2c.onrender.com/ws/video 