services:
  - type: web
    name: video-stream-backend
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && python3 main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: https://video-stream-frontend-lexb.onrender.com
      - key: ENVIRONMENT
        value: production

  - type: web
    name: video-stream-frontend
    env: static
    rootDir: frontend
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    envVars:
      - key: VITE_WS_URL
        value: wss://video-stream-backend-jr2c.onrender.com/ws/video 