services:
  - type: web
    name: video-stream-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: https://video-stream-frontend.onrender.com

  - type: static
    name: video-stream-frontend
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WS_URL
        value: wss://video-stream-backend.onrender.com/ws/video 